/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Accesos extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Accesos() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter(){
                
                @Override
                public void windowClosing(WindowEvent e){
                    int x = JOptionPane.showConfirmDialog(null, "¿Realmemte quiere salir de KeLiz System?",
                                                          "Cerrar",
                                                          JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if(x == JOptionPane.YES_OPTION){
                        e.getWindow().dispose();
                        System.out.println("Cerrar");
                    }else if(x == JOptionPane.NO_OPTION){
                        System.out.println("Seguimo'");
                    }
                }
        });
        setTitle("KeLiz System - Reportes");
        setIconImage(new ImageIcon(getClass().getResource("/findingpeople/Images/loginImage.png")).getImage());
        this.setResizable(false);
        setFrameCenter(this);
        panel_Usuarios.hide();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_FondoAccesos = new javax.swing.JPanel();
        panel_Titulos = new javax.swing.JPanel();
        button_Administradores = new javax.swing.JButton();
        button_Usuarios = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_Administradores = new javax.swing.JPanel();
        label_Administradores = new javax.swing.JLabel();
        button_MenuPrincipalEnAdministradores = new javax.swing.JButton();
        panel_Usuarios = new javax.swing.JPanel();
        label_PersonasEncontradas = new javax.swing.JLabel();
        button_MenuPrincipalEnUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Titulos.setBackground(new java.awt.Color(0, 0, 204));

        button_Administradores.setBackground(new java.awt.Color(4, 96, 194));
        button_Administradores.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        button_Administradores.setForeground(new java.awt.Color(255, 255, 255));
        button_Administradores.setText("Administradores");
        button_Administradores.setBorder(null);
        button_Administradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AdministradoresActionPerformed(evt);
            }
        });

        button_Usuarios.setBackground(new java.awt.Color(0, 204, 102));
        button_Usuarios.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        button_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        button_Usuarios.setText("Usuarios");
        button_Usuarios.setBorder(null);
        button_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TitulosLayout = new javax.swing.GroupLayout(panel_Titulos);
        panel_Titulos.setLayout(panel_TitulosLayout);
        panel_TitulosLayout.setHorizontalGroup(
            panel_TitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TitulosLayout.createSequentialGroup()
                .addComponent(button_Administradores, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_TitulosLayout.setVerticalGroup(
            panel_TitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_Administradores, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(button_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Administradores.setBackground(new java.awt.Color(37, 47, 65));

        label_Administradores.setText("Aqui va la lista de usuarios administradores");

        button_MenuPrincipalEnAdministradores.setBackground(new java.awt.Color(4, 96, 194));
        button_MenuPrincipalEnAdministradores.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_MenuPrincipalEnAdministradores.setForeground(new java.awt.Color(225, 225, 225));
        button_MenuPrincipalEnAdministradores.setText("Menu Principal");
        button_MenuPrincipalEnAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MenuPrincipalEnAdministradoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_AdministradoresLayout = new javax.swing.GroupLayout(panel_Administradores);
        panel_Administradores.setLayout(panel_AdministradoresLayout);
        panel_AdministradoresLayout.setHorizontalGroup(
            panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AdministradoresLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_AdministradoresLayout.createSequentialGroup()
                        .addComponent(button_MenuPrincipalEnAdministradores)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_AdministradoresLayout.createSequentialGroup()
                        .addComponent(label_Administradores, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))))
        );
        panel_AdministradoresLayout.setVerticalGroup(
            panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AdministradoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MenuPrincipalEnAdministradores)
                .addGap(73, 73, 73)
                .addComponent(label_Administradores, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_Administradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 809, -1));

        panel_Usuarios.setBackground(new java.awt.Color(37, 47, 65));

        label_PersonasEncontradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_PersonasEncontradas.setText("Aqui va la lista de usuarios");

        button_MenuPrincipalEnUsuarios.setBackground(new java.awt.Color(4, 96, 194));
        button_MenuPrincipalEnUsuarios.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_MenuPrincipalEnUsuarios.setForeground(new java.awt.Color(225, 225, 225));
        button_MenuPrincipalEnUsuarios.setText("Menu Principal");
        button_MenuPrincipalEnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MenuPrincipalEnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_UsuariosLayout = new javax.swing.GroupLayout(panel_Usuarios);
        panel_Usuarios.setLayout(panel_UsuariosLayout);
        panel_UsuariosLayout.setHorizontalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_UsuariosLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(label_PersonasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_UsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_MenuPrincipalEnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_UsuariosLayout.setVerticalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MenuPrincipalEnUsuarios)
                .addGap(92, 92, 92)
                .addComponent(label_PersonasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout panel_FondoAccesosLayout = new javax.swing.GroupLayout(panel_FondoAccesos);
        panel_FondoAccesos.setLayout(panel_FondoAccesosLayout);
        panel_FondoAccesosLayout.setHorizontalGroup(
            panel_FondoAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Titulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        panel_FondoAccesosLayout.setVerticalGroup(
            panel_FondoAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FondoAccesosLayout.createSequentialGroup()
                .addComponent(panel_Titulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_FondoAccesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_FondoAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_AdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AdministradoresActionPerformed
        button_Administradores.setFont(new Font("Tahoma", 1, 22));
        button_Usuarios.setFont(new Font("Tahoma", 1, 20));
        panel_Administradores.show();
        panel_Usuarios.hide();
    }//GEN-LAST:event_button_AdministradoresActionPerformed

    private void button_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UsuariosActionPerformed

        button_Administradores.setFont(new Font("Tahoma", 1, 20));
        button_Usuarios.setFont(new Font("Tahoma", 1, 22));
        panel_Administradores.hide();
        panel_Usuarios.show();

    }//GEN-LAST:event_button_UsuariosActionPerformed

    private void button_MenuPrincipalEnAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MenuPrincipalEnAdministradoresActionPerformed
        Container container = new Container();
        this.hide();
        container.show();
    }//GEN-LAST:event_button_MenuPrincipalEnAdministradoresActionPerformed

    private void button_MenuPrincipalEnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MenuPrincipalEnUsuariosActionPerformed
        Container container = new Container();
        this.hide();
        container.show();
    }//GEN-LAST:event_button_MenuPrincipalEnUsuariosActionPerformed

    private void setFrameCenter(JFrame f) {

        Toolkit toolkit = getToolkit();
        Dimension tamanoPantalla = toolkit.getScreenSize();
        f.setLocation((tamanoPantalla.width / 2) - (getWidth() / 2), (tamanoPantalla.height / 2) - (getHeight() / 2));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Administradores;
    private javax.swing.JButton button_MenuPrincipalEnAdministradores;
    private javax.swing.JButton button_MenuPrincipalEnUsuarios;
    private javax.swing.JButton button_Usuarios;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel label_Administradores;
    private javax.swing.JLabel label_PersonasEncontradas;
    private javax.swing.JPanel panel_Administradores;
    private javax.swing.JPanel panel_FondoAccesos;
    private javax.swing.JPanel panel_Titulos;
    private javax.swing.JPanel panel_Usuarios;
    // End of variables declaration//GEN-END:variables
}
