/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import findingpeople.util.CommonsFrame;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ConexionBD;

/**
 *
 * @author USER
 */
public class Accesos extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Accesos() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                int x = JOptionPane.showConfirmDialog(null, "¿Realmemte quiere salir de KeLiz System?",
                        "Cerrar",
                        JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (x == JOptionPane.YES_OPTION) {
                    e.getWindow().dispose();
                    System.out.println("Cerrar");
                } else if (x == JOptionPane.NO_OPTION) {
                    System.out.println("Seguimo'");
                }
            }
        });

        setIconImage(new ImageIcon(getClass().getResource("/findingpeople/Images/loginImage.png")).getImage());
        CommonsFrame.setFrameCenter(this);
        CommonsFrame.frameAtributes(this);
        panel_Administradores.hide();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_FondoAccesos = new javax.swing.JPanel();
        panel_Titulos = new javax.swing.JPanel();
        button_Administradores = new javax.swing.JButton();
        button_Usuarios = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_Usuarios = new javax.swing.JPanel();
        button_MenuPrincipalEnUsuarios = new javax.swing.JButton();
        input_NombreInAccesosUsuarios = new javax.swing.JTextField();
        label_NombreInUsuarios = new javax.swing.JLabel();
        button_CargarDatosUsuarios = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Usuarios = new javax.swing.JTable();
        panel_Administradores = new javax.swing.JPanel();
        button_MenuPrincipalEnAdministradores1 = new javax.swing.JButton();
        input_NombreInAccesosAdministradores = new javax.swing.JTextField();
        label_Nombre = new javax.swing.JLabel();
        button_CargarDatosAdministradores = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_Administradores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Titulos.setBackground(new java.awt.Color(0, 0, 204));

        button_Administradores.setBackground(new java.awt.Color(4, 96, 194));
        button_Administradores.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        button_Administradores.setForeground(new java.awt.Color(255, 255, 255));
        button_Administradores.setText("Usuarios");
        button_Administradores.setBorder(null);
        button_Administradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AdministradoresActionPerformed(evt);
            }
        });

        button_Usuarios.setBackground(new java.awt.Color(0, 204, 102));
        button_Usuarios.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        button_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        button_Usuarios.setText("Administradores");
        button_Usuarios.setBorder(null);
        button_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TitulosLayout = new javax.swing.GroupLayout(panel_Titulos);
        panel_Titulos.setLayout(panel_TitulosLayout);
        panel_TitulosLayout.setHorizontalGroup(
            panel_TitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TitulosLayout.createSequentialGroup()
                .addComponent(button_Administradores, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_TitulosLayout.setVerticalGroup(
            panel_TitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_Administradores, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(button_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Usuarios.setBackground(new java.awt.Color(37, 47, 65));

        button_MenuPrincipalEnUsuarios.setBackground(new java.awt.Color(4, 96, 194));
        button_MenuPrincipalEnUsuarios.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_MenuPrincipalEnUsuarios.setForeground(new java.awt.Color(225, 225, 225));
        button_MenuPrincipalEnUsuarios.setText("Menu Principal");
        button_MenuPrincipalEnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MenuPrincipalEnUsuariosActionPerformed(evt);
            }
        });

        input_NombreInAccesosUsuarios.setToolTipText("");
        input_NombreInAccesosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_NombreInAccesosUsuariosActionPerformed(evt);
            }
        });

        label_NombreInUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_NombreInUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        label_NombreInUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_NombreInUsuarios.setText("NOMBRE:");

        button_CargarDatosUsuarios.setText("Cargar Datos");
        button_CargarDatosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CargarDatosUsuariosActionPerformed(evt);
            }
        });

        table_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Usuario", "Contraseña", "Telefono", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_Usuarios);

        javax.swing.GroupLayout panel_UsuariosLayout = new javax.swing.GroupLayout(panel_Usuarios);
        panel_Usuarios.setLayout(panel_UsuariosLayout);
        panel_UsuariosLayout.setHorizontalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_UsuariosLayout.createSequentialGroup()
                        .addGap(0, 674, Short.MAX_VALUE)
                        .addComponent(button_MenuPrincipalEnUsuarios))
                    .addGroup(panel_UsuariosLayout.createSequentialGroup()
                        .addComponent(label_NombreInUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_NombreInAccesosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_CargarDatosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        panel_UsuariosLayout.setVerticalGroup(
            panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MenuPrincipalEnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_NombreInUsuarios)
                        .addComponent(input_NombreInAccesosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_CargarDatosUsuarios))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 809, -1));

        panel_Administradores.setBackground(new java.awt.Color(37, 47, 65));

        button_MenuPrincipalEnAdministradores1.setBackground(new java.awt.Color(4, 96, 194));
        button_MenuPrincipalEnAdministradores1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_MenuPrincipalEnAdministradores1.setForeground(new java.awt.Color(225, 225, 225));
        button_MenuPrincipalEnAdministradores1.setText("Menu Principal");
        button_MenuPrincipalEnAdministradores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MenuPrincipalEnAdministradores1ActionPerformed(evt);
            }
        });

        input_NombreInAccesosAdministradores.setToolTipText("");

        label_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        label_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_Nombre.setText("NOMBRE:");

        button_CargarDatosAdministradores.setText("Cargar Datos");
        button_CargarDatosAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CargarDatosAdministradoresActionPerformed(evt);
            }
        });

        table_Administradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Usuario", "Contraseña", "Telefono", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(table_Administradores);

        javax.swing.GroupLayout panel_AdministradoresLayout = new javax.swing.GroupLayout(panel_Administradores);
        panel_Administradores.setLayout(panel_AdministradoresLayout);
        panel_AdministradoresLayout.setHorizontalGroup(
            panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AdministradoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_AdministradoresLayout.createSequentialGroup()
                        .addGap(0, 674, Short.MAX_VALUE)
                        .addComponent(button_MenuPrincipalEnAdministradores1))
                    .addGroup(panel_AdministradoresLayout.createSequentialGroup()
                        .addComponent(label_Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(input_NombreInAccesosAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_CargarDatosAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panel_AdministradoresLayout.setVerticalGroup(
            panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AdministradoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MenuPrincipalEnAdministradores1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_AdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_Nombre)
                        .addComponent(input_NombreInAccesosAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_CargarDatosAdministradores))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_Administradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout panel_FondoAccesosLayout = new javax.swing.GroupLayout(panel_FondoAccesos);
        panel_FondoAccesos.setLayout(panel_FondoAccesosLayout);
        panel_FondoAccesosLayout.setHorizontalGroup(
            panel_FondoAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Titulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        panel_FondoAccesosLayout.setVerticalGroup(
            panel_FondoAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FondoAccesosLayout.createSequentialGroup()
                .addComponent(panel_Titulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_FondoAccesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_FondoAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_AdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AdministradoresActionPerformed
        button_Administradores.setFont(new Font("Tahoma", 1, 22));
        button_Usuarios.setFont(new Font("Tahoma", 1, 20));
        panel_Usuarios.show();
        panel_Administradores.hide();
    }//GEN-LAST:event_button_AdministradoresActionPerformed

    private void button_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UsuariosActionPerformed

        button_Administradores.setFont(new Font("Tahoma", 1, 20));
        button_Usuarios.setFont(new Font("Tahoma", 1, 22));
        panel_Usuarios.hide();
        panel_Administradores.show();

    }//GEN-LAST:event_button_UsuariosActionPerformed

    private void button_MenuPrincipalEnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MenuPrincipalEnUsuariosActionPerformed
        Container container = new Container();
        this.hide();
        container.show();
    }//GEN-LAST:event_button_MenuPrincipalEnUsuariosActionPerformed

    private void button_CargarDatosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CargarDatosUsuariosActionPerformed
        cargarDatosDeUsuarios();
    }//GEN-LAST:event_button_CargarDatosUsuariosActionPerformed

    private void button_MenuPrincipalEnAdministradores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MenuPrincipalEnAdministradores1ActionPerformed
        Container container = new Container();
        this.hide();
        container.show();
    }//GEN-LAST:event_button_MenuPrincipalEnAdministradores1ActionPerformed

    private void button_CargarDatosAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CargarDatosAdministradoresActionPerformed
        cargarDatosDeAdministradores();
    }//GEN-LAST:event_button_CargarDatosAdministradoresActionPerformed

    private void input_NombreInAccesosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_NombreInAccesosUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_NombreInAccesosUsuariosActionPerformed

    private void setFrameCenter(JFrame f) {

        Toolkit toolkit = getToolkit();
        Dimension tamanoPantalla = toolkit.getScreenSize();
        f.setLocation((tamanoPantalla.width / 2) - (getWidth() / 2), (tamanoPantalla.height / 2) - (getHeight() / 2));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Administradores;
    private javax.swing.JButton button_CargarDatosAdministradores;
    private javax.swing.JButton button_CargarDatosUsuarios;
    private javax.swing.JButton button_MenuPrincipalEnAdministradores1;
    private javax.swing.JButton button_MenuPrincipalEnUsuarios;
    private javax.swing.JButton button_Usuarios;
    private javax.swing.JTextField input_NombreInAccesosAdministradores;
    private javax.swing.JTextField input_NombreInAccesosUsuarios;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_NombreInUsuarios;
    private javax.swing.JPanel panel_Administradores;
    private javax.swing.JPanel panel_FondoAccesos;
    private javax.swing.JPanel panel_Titulos;
    private javax.swing.JPanel panel_Usuarios;
    private javax.swing.JTable table_Administradores;
    private javax.swing.JTable table_Usuarios;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosDeAdministradores() {

        //    https://www.youtube.com/watch?v=MyO_AiU7cEM //Agradeceme despues
        //validar que el Id no venga vacio para la consulta
        String campo = input_NombreInAccesosAdministradores.getText();
        String where = "";
        if (!"".equals(campo)) {

            where = "WHERE nombre = '" + campo + "'";

        }

        try {

            DefaultTableModel modelo = new DefaultTableModel();
            table_Administradores.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionBD conexion = new ConexionBD();
            Connection con = conexion.conectar();

            String sql = "SELECT nombre, usuario, contrasena, telefono, sexo FROM administradores " + where;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsmd = rs.getMetaData();
            int cantidadColumnas = rsmd.getColumnCount();

            //Colocar las columnas
            modelo.addColumn("Nombre");
            modelo.addColumn("Usuario");
            modelo.addColumn("Contraseña");
            modelo.addColumn("Telefono");
            modelo.addColumn("Sexo");

            //Colocando tamano a nuestras columnas
            int anchos[] = {200, 150, 200, 150, 60};

            for (int x = 0; x < cantidadColumnas; x++) {
                table_Administradores.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumnas];

                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }

                modelo.addRow(filas);

            }

        } catch (Exception e) {
            System.out.println("Error al cargar los datos a la tabla de Administradores");
            e.printStackTrace();
        }

    }

    private void cargarDatosDeUsuarios() {

        //    https://www.youtube.com/watch?v=MyO_AiU7cEM //Agradeceme despues
        //validar que el Id no venga vacio para la consulta
        String campo = input_NombreInAccesosUsuarios.getText();
        String where = "";
        if (!"".equals(campo)) {

            where = "WHERE nombre = '" + campo + "'";

        }

        try {

            DefaultTableModel modelo = new DefaultTableModel();
            table_Usuarios.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionBD conexion = new ConexionBD();
            Connection con = conexion.conectar();

            String sql = "SELECT nombre, usuario, contrasena, telefono, sexo FROM usuarios " + where;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsmd = rs.getMetaData();
            int cantidadColumnas = rsmd.getColumnCount();

            //Colocar las columnas
            modelo.addColumn("Nombre");
            modelo.addColumn("Usuario");
            modelo.addColumn("Contraseña");
            modelo.addColumn("Telefono");
            modelo.addColumn("Sexo");

            //Colocando tamano a nuestras columnas
            int anchos[] = {200, 150, 200, 150, 60};

            for (int x = 0; x < cantidadColumnas; x++) {
                table_Usuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumnas];

                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }

                modelo.addRow(filas);

            }

        } catch (Exception e) {
            System.out.println("Error al cargar los datos a la tabla de Usuarios");
            e.printStackTrace();
        }

    }

}
