/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class Container extends javax.swing.JFrame {

    Login login = new Login();

    /**
     * Creates new form Container
     */
    public Container() {
        initComponents();
        setFrameCenter(this);
        setTitle("Finding People CO.");
        setResizable(false);
        //  setExtendedState(MAXIMIZED_BOTH);
        button_RegistrarPersonaDesaparecida.setIcon(setIconInButtonPresioned("Images/EncontrarPersonaImagen.png", button_RegistrarPersonaDesaparecida,20,20));
        button_RegistrarPersonaDesaparecida.setIcon(setIconInButton("Images/EncontrarPersonaImagen.png", button_RegistrarPersonaDesaparecida));
    }

    public void setFrameCenter(JFrame f) {

        Toolkit toolkit = getToolkit();
        Dimension tamanoPantalla = toolkit.getScreenSize();
        f.setLocation((tamanoPantalla.width / 2) - (getWidth() / 2), (tamanoPantalla.height / 2) - (getHeight() / 2));

    }

    private void setImagenJLabel(JLabel label, String ruta) {

        // El codigo esta explicado en este video (https://www.youtube.com/watch?v=G3QJqbYuJ7M)
        ImageIcon miImageIcon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta)));
        Image img1 = miImageIcon.getImage();
        Image img2 = img1.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        label.setIcon(i);
    }

    private Icon setIconInButton(String ruta, JButton button) {

        ImageIcon icon = new ImageIcon(getClass().getResource(ruta));
        int ancho = button.getWidth();
        int alto = button.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }

        private Icon setIconInButtonPresioned(String ruta, JButton button,int ancho, int altura) {

        ImageIcon icon = new ImageIcon(getClass().getResource(ruta));
        int width = button.getWidth() - ancho;
        int height = button.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));

        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Container = new javax.swing.JPanel();
        button_EncontrarPersonaDesaparecida = new javax.swing.JButton();
        label_EncontrarPersonaDesaparecida = new javax.swing.JLabel();
        button_SimulacionEnTiempoReal = new javax.swing.JButton();
        label_SimulacionEnTiempoReal = new javax.swing.JLabel();
        button_RegistrarPersonaDesaparecida = new javax.swing.JButton();
        label_RegistrarPersonaDesaparecida = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label_CuadroFondoDeRegistrarPersonaDesaparecida = new javax.swing.JLabel();
        label_ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(1000, 650));

        panel_Container.setBackground(new java.awt.Color(102, 255, 102));
        panel_Container.setMaximumSize(null);
        panel_Container.setPreferredSize(new java.awt.Dimension(1000, 650));
        panel_Container.setLayout(null);

        button_EncontrarPersonaDesaparecida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findingpeople/Images/FaceRecognition.jpg"))); // NOI18N
        button_EncontrarPersonaDesaparecida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EncontrarPersonaDesaparecidaActionPerformed(evt);
            }
        });
        panel_Container.add(button_EncontrarPersonaDesaparecida);
        button_EncontrarPersonaDesaparecida.setBounds(450, 160, 200, 130);

        label_EncontrarPersonaDesaparecida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_EncontrarPersonaDesaparecida.setText("Encontrar Persona Desaparecida");
        panel_Container.add(label_EncontrarPersonaDesaparecida);
        label_EncontrarPersonaDesaparecida.setBounds(460, 300, 180, 40);

        button_SimulacionEnTiempoReal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findingpeople/Images/FaceRecognition.jpg"))); // NOI18N
        button_SimulacionEnTiempoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SimulacionEnTiempoRealActionPerformed(evt);
            }
        });
        panel_Container.add(button_SimulacionEnTiempoReal);
        button_SimulacionEnTiempoReal.setBounds(690, 160, 200, 130);

        label_SimulacionEnTiempoReal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_SimulacionEnTiempoReal.setText("Simulacion en tiempo real");
        panel_Container.add(label_SimulacionEnTiempoReal);
        label_SimulacionEnTiempoReal.setBounds(700, 300, 180, 40);

        button_RegistrarPersonaDesaparecida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findingpeople/Images/EncontrarPersonaImagen.png"))); // NOI18N
        button_RegistrarPersonaDesaparecida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_RegistrarPersonaDesaparecida.setMaximumSize(new java.awt.Dimension(100, 200));
        button_RegistrarPersonaDesaparecida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RegistrarPersonaDesaparecidaActionPerformed(evt);
            }
        });
        panel_Container.add(button_RegistrarPersonaDesaparecida);
        button_RegistrarPersonaDesaparecida.setBounds(60, 120, 260, 170);

        label_RegistrarPersonaDesaparecida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_RegistrarPersonaDesaparecida.setForeground(new java.awt.Color(255, 255, 255));
        label_RegistrarPersonaDesaparecida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_RegistrarPersonaDesaparecida.setText("Registrar Persona Desaparecida");
        panel_Container.add(label_RegistrarPersonaDesaparecida);
        label_RegistrarPersonaDesaparecida.setBounds(80, 310, 218, 40);

        jButton2.setText("Reportes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_Container.add(jButton2);
        jButton2.setBounds(80, 20, 120, 23);

        jButton3.setText("Cerrar Sesion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_Container.add(jButton3);
        jButton3.setBounds(660, 20, 120, 23);

        label_CuadroFondoDeRegistrarPersonaDesaparecida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findingpeople/Images/BlueFondo.jpg"))); // NOI18N
        panel_Container.add(label_CuadroFondoDeRegistrarPersonaDesaparecida);
        label_CuadroFondoDeRegistrarPersonaDesaparecida.setBounds(40, 100, 300, 280);

        label_ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findingpeople/Images/ContainerFondo.jpeg"))); // NOI18N
        panel_Container.add(label_ImagenFondo);
        label_ImagenFondo.setBounds(0, 0, 1290, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_RegistrarPersonaDesaparecidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RegistrarPersonaDesaparecidaActionPerformed

        UploadPeople uploadPeople = new UploadPeople();
        this.hide();
        uploadPeople.show();

        // TODO add your handling code here:
    }//GEN-LAST:event_button_RegistrarPersonaDesaparecidaActionPerformed

    private void button_EncontrarPersonaDesaparecidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EncontrarPersonaDesaparecidaActionPerformed
        System.out.println("Esta wea funciona");        // TODO add your handling code here:
    }//GEN-LAST:event_button_EncontrarPersonaDesaparecidaActionPerformed

    private void button_SimulacionEnTiempoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SimulacionEnTiempoRealActionPerformed
        System.out.println("Esta wea funciona");        // TODO add your handling code here:
    }//GEN-LAST:event_button_SimulacionEnTiempoRealActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Reports reports = new Reports();
        this.hide();
        reports.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Login login = new Login();
        this.hide();
        login.show();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Container().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_EncontrarPersonaDesaparecida;
    private javax.swing.JButton button_RegistrarPersonaDesaparecida;
    private javax.swing.JButton button_SimulacionEnTiempoReal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel label_CuadroFondoDeRegistrarPersonaDesaparecida;
    private javax.swing.JLabel label_EncontrarPersonaDesaparecida;
    private javax.swing.JLabel label_ImagenFondo;
    private javax.swing.JLabel label_RegistrarPersonaDesaparecida;
    private javax.swing.JLabel label_SimulacionEnTiempoReal;
    private javax.swing.JPanel panel_Container;
    // End of variables declaration//GEN-END:variables
}
