/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import findingpeople.util.CommonsFrame;

/**
 *
 * @author USER
 */
public class EncontrarDesaparecido extends javax.swing.JFrame {

    /**
     * Creates new form EncontrarDesaparecido
     */
    public EncontrarDesaparecido() {
        initComponents();
        CommonsFrame.setFrameCenter(this);
        CommonsFrame.frameAtributes(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button_EncontrarConKeliz = new javax.swing.JButton();
        button_Mesientoconsuerte = new javax.swing.JButton();
        label_PersonaDesaparecida = new javax.swing.JLabel();
        label_NombreDesaparecido = new javax.swing.JLabel();
        label_mensajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 47, 65));

        button_EncontrarConKeliz.setBackground(new java.awt.Color(4, 96, 194));
        button_EncontrarConKeliz.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_EncontrarConKeliz.setForeground(new java.awt.Color(225, 225, 225));
        button_EncontrarConKeliz.setText("Encontrar con Keliz");
        button_EncontrarConKeliz.setEnabled(false);
        button_EncontrarConKeliz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EncontrarConKelizActionPerformed(evt);
            }
        });

        button_Mesientoconsuerte.setBackground(new java.awt.Color(4, 96, 194));
        button_Mesientoconsuerte.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_Mesientoconsuerte.setForeground(new java.awt.Color(225, 225, 225));
        button_Mesientoconsuerte.setText("Me siento con suete");
        button_Mesientoconsuerte.setEnabled(false);
        button_Mesientoconsuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MesientoconsuerteActionPerformed(evt);
            }
        });

        label_PersonaDesaparecida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        label_NombreDesaparecido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_NombreDesaparecido.setForeground(new java.awt.Color(255, 255, 255));
        label_NombreDesaparecido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label_mensajes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_mensajes.setForeground(new java.awt.Color(255, 0, 0));
        label_mensajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(button_EncontrarConKeliz, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_Mesientoconsuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_PersonaDesaparecida, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(label_NombreDesaparecido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(label_mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(label_NombreDesaparecido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_PersonaDesaparecida, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Mesientoconsuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_EncontrarConKeliz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_EncontrarConKelizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EncontrarConKelizActionPerformed

    }//GEN-LAST:event_button_EncontrarConKelizActionPerformed

    private void button_MesientoconsuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MesientoconsuerteActionPerformed


    }//GEN-LAST:event_button_MesientoconsuerteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncontrarDesaparecido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncontrarDesaparecido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncontrarDesaparecido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncontrarDesaparecido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncontrarDesaparecido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_EncontrarConKeliz;
    private javax.swing.JButton button_Mesientoconsuerte;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel label_NombreDesaparecido;
    public static javax.swing.JLabel label_PersonaDesaparecida;
    private javax.swing.JLabel label_mensajes;
    // End of variables declaration//GEN-END:variables
}
