/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {

    private boolean signInvalidate = false;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        panel_Loanding.hide();
        panel_Register.hide();
        PlaceHolder holder = new PlaceHolder("User", input_User);
        PlaceHolder holder2 = new PlaceHolder("Password", input_Password);
        setFrameCenter(this);
        setTitle("Finding People CO.");
        setResizable(false);
        setImagenJLabel(label_LoginImage, "Images/FaceRecognition.jpg");
        setImagenJLabel(label_IconoUser, "Images/UserTxtUser.png");
        setImagenJLabel(label_IconoPassword, "Images/PasswordImage.png");
        setImagenJLabel(label_IconoSignIn, "Images/SignInIcon.png");
        //setImagenJLabel(label_IconoSignIn,"Images/SignInImage.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_ContendorLogin = new javax.swing.JPanel();
        panel_EsteticaLogin = new javax.swing.JPanel();
        panel_ImageLogin = new javax.swing.JPanel();
        label_LoginImage = new javax.swing.JLabel();
        label_ProyectName = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        panel_Loanding = new javax.swing.JPanel();
        rSProgressMaterial1 = new rojerusan.componentes.RSProgressMaterial();
        lblCargando = new javax.swing.JLabel();
        lblCargando1 = new javax.swing.JLabel();
        panel_InfoLogin = new javax.swing.JPanel();
        panel_Login = new javax.swing.JPanel();
        label_SignIn = new javax.swing.JLabel();
        input_User = new javax.swing.JTextField();
        input_Password = new javax.swing.JPasswordField();
        button_Login = new rojeru_san.RSButton();
        check_RemenberMe = new javax.swing.JCheckBox();
        separator_Separator1 = new javax.swing.JSeparator();
        label_DontHaveAccount = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        label_IconoSignIn = new javax.swing.JLabel();
        label_IconoUser = new javax.swing.JLabel();
        label_IconoPassword = new javax.swing.JLabel();
        label_ValidacionesTxt = new javax.swing.JLabel();
        button_RegisterHere = new javax.swing.JButton();
        button_RegisterHere1 = new javax.swing.JButton();
        panel_Register = new javax.swing.JPanel();
        label_IconoSignIn1 = new javax.swing.JLabel();
        label_SignIn1 = new javax.swing.JLabel();
        input_User1 = new javax.swing.JTextField();
        input_Password1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_EsteticaLogin.setBackground(new java.awt.Color(97, 212, 195));
        panel_EsteticaLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_ImageLogin.setBackground(new java.awt.Color(97, 212, 195));

        label_LoginImage.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label_LoginImage.setForeground(new java.awt.Color(255, 255, 255));
        label_LoginImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_LoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/findingpeople/Images/FaceRecognition.jpg"))); // NOI18N

        label_ProyectName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        label_ProyectName.setForeground(new java.awt.Color(255, 255, 255));
        label_ProyectName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ProyectName.setText("Finding People");

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_ImageLoginLayout = new javax.swing.GroupLayout(panel_ImageLogin);
        panel_ImageLogin.setLayout(panel_ImageLoginLayout);
        panel_ImageLoginLayout.setHorizontalGroup(
            panel_ImageLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(panel_ImageLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ImageLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panel_ImageLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_ImageLoginLayout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(label_ProyectName))
                        .addComponent(label_LoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_ImageLoginLayout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_ImageLoginLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_ImageLoginLayout.setVerticalGroup(
            panel_ImageLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(panel_ImageLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ImageLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_ProyectName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(76, 76, 76)
                    .addComponent(label_LoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_EsteticaLogin.add(panel_ImageLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 530));

        panel_Loanding.setBackground(new java.awt.Color(97, 212, 195));

        rSProgressMaterial1.setForeground(new java.awt.Color(37, 47, 65));
        rSProgressMaterial1.setAnchoProgress(20);
        rSProgressMaterial1.setPreferredSize(new java.awt.Dimension(100, 100));

        lblCargando.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCargando.setForeground(new java.awt.Color(37, 47, 65));
        lblCargando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargando.setText("Espere un momento");

        lblCargando1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCargando1.setForeground(new java.awt.Color(37, 47, 65));
        lblCargando1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargando1.setText("Cargando...");

        javax.swing.GroupLayout panel_LoandingLayout = new javax.swing.GroupLayout(panel_Loanding);
        panel_Loanding.setLayout(panel_LoandingLayout);
        panel_LoandingLayout.setHorizontalGroup(
            panel_LoandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoandingLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(panel_LoandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCargando, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(lblCargando1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
        );
        panel_LoandingLayout.setVerticalGroup(
            panel_LoandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LoandingLayout.createSequentialGroup()
                .addComponent(rSProgressMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblCargando1)
                .addGap(8, 8, 8)
                .addComponent(lblCargando))
        );

        panel_EsteticaLogin.add(panel_Loanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 430, 290));

        panel_InfoLogin.setBackground(new java.awt.Color(37, 47, 65));
        panel_InfoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Login.setBackground(new java.awt.Color(37, 47, 65));

        label_SignIn.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        label_SignIn.setForeground(new java.awt.Color(204, 204, 204));
        label_SignIn.setText("Sign In");

        button_Login.setBackground(new java.awt.Color(37, 47, 65));
        button_Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(37, 25, 97), new java.awt.Color(37, 25, 97)));
        button_Login.setText("Login");
        button_Login.setColorHover(new java.awt.Color(37, 50, 65));
        button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LoginActionPerformed(evt);
            }
        });

        check_RemenberMe.setBackground(new java.awt.Color(37, 47, 65));
        check_RemenberMe.setForeground(new java.awt.Color(255, 255, 255));
        check_RemenberMe.setSelected(true);
        check_RemenberMe.setText("Remerber me");
        check_RemenberMe.setBorder(null);
        check_RemenberMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_RemenberMeActionPerformed(evt);
            }
        });

        separator_Separator1.setForeground(new java.awt.Color(255, 255, 255));

        label_DontHaveAccount.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        label_DontHaveAccount.setForeground(new java.awt.Color(255, 255, 255));
        label_DontHaveAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_DontHaveAccount.setText("Don't have an account?");

        label_ValidacionesTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_ValidacionesTxt.setForeground(new java.awt.Color(255, 0, 0));
        label_ValidacionesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ValidacionesTxt.setText(" ");

        button_RegisterHere.setBackground(new java.awt.Color(37, 47, 65));
        button_RegisterHere.setForeground(new java.awt.Color(255, 255, 255));
        button_RegisterHere.setText("REGISTER HERE");
        button_RegisterHere.setBorder(null);
        button_RegisterHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RegisterHereActionPerformed(evt);
            }
        });

        button_RegisterHere1.setBackground(new java.awt.Color(37, 47, 65));
        button_RegisterHere1.setForeground(new java.awt.Color(255, 255, 255));
        button_RegisterHere1.setText("Forgot Password?");
        button_RegisterHere1.setBorder(null);

        javax.swing.GroupLayout panel_LoginLayout = new javax.swing.GroupLayout(panel_Login);
        panel_Login.setLayout(panel_LoginLayout);
        panel_LoginLayout.setHorizontalGroup(
            panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(check_RemenberMe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_RegisterHere1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                        .addComponent(label_DontHaveAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_RegisterHere, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
            .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_LoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_LoginLayout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(label_IconoSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_LoginLayout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(label_SignIn))
                        .addGroup(panel_LoginLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(label_IconoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(input_User, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_LoginLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(label_IconoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(input_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_LoginLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(label_ValidacionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_LoginLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(separator_Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_LoginLayout.setVerticalGroup(
            panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_RegisterHere1)
                    .addComponent(check_RemenberMe))
                .addGap(40, 40, 40)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_RegisterHere)
                    .addComponent(label_DontHaveAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_LoginLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(label_IconoSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)
                    .addComponent(label_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_IconoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_User, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_LoginLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(label_IconoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(input_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addComponent(label_ValidacionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)
                    .addComponent(button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addComponent(separator_Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 56, Short.MAX_VALUE)))
        );

        panel_InfoLogin.add(panel_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_Register.setBackground(new java.awt.Color(37, 47, 65));

        label_SignIn1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        label_SignIn1.setForeground(new java.awt.Color(204, 204, 204));
        label_SignIn1.setText("Sign In");

        javax.swing.GroupLayout panel_RegisterLayout = new javax.swing.GroupLayout(panel_Register);
        panel_Register.setLayout(panel_RegisterLayout);
        panel_RegisterLayout.setHorizontalGroup(
            panel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RegisterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_RegisterLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(label_IconoSignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_RegisterLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(label_SignIn1))
                    .addComponent(input_User1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_RegisterLayout.setVerticalGroup(
            panel_RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RegisterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_IconoSignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(label_SignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input_User1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(input_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_InfoLogin.add(panel_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 530));

        javax.swing.GroupLayout panel_ContendorLoginLayout = new javax.swing.GroupLayout(panel_ContendorLogin);
        panel_ContendorLogin.setLayout(panel_ContendorLoginLayout);
        panel_ContendorLoginLayout.setHorizontalGroup(
            panel_ContendorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ContendorLoginLayout.createSequentialGroup()
                .addComponent(panel_EsteticaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_InfoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ContendorLoginLayout.setVerticalGroup(
            panel_ContendorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_EsteticaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_InfoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ContendorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ContendorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LoginActionPerformed
        validateEmptyFields();
    }//GEN-LAST:event_button_LoginActionPerformed

    private void check_RemenberMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_RemenberMeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_RemenberMeActionPerformed

    private void button_RegisterHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RegisterHereActionPerformed
        panel_Login.hide();
        panel_Register.show();
    }//GEN-LAST:event_button_RegisterHereActionPerformed

    private void setImagenJLabel(JLabel label, String ruta) {

        // El codigo esta explicado en este video (https://www.youtube.com/watch?v=G3QJqbYuJ7M)
        ImageIcon miImageIcon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta)));
        Image img1 = miImageIcon.getImage();
        Image img2 = img1.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        label.setIcon(i);
    }

    
    private void validateEmptyFields() {
        if (input_User.getText().isEmpty() || input_Password.getText().isEmpty()) {
            label_ValidacionesTxt.setText("No puede estar vacío!");
        } else {
            label_ValidacionesTxt.setText("");
            signInvalidate = true;
            signIn();
        }
    }

    private void signIn() {
        if (signInvalidate) {
            if (input_User.getText().equals("kel") && input_Password.getText().equals("123")) {
                mostrarPanelCargandoEIngresar();
            }
        } else {
            System.out.println("Algo anda mal en el log in");
        }
    }

    private void mostrarPanelCargandoEIngresar() {
        label_LoginImage.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                            new java.net.URL("file:/C:/Users/USER/EstaImagenNoExiste.png") // Da error y no la encuentra fue aproposito
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        panel_Loanding.show();
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(3000);
                    dispose();
                    new Container().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }

    private void setFrameCenter(JFrame f) {

        Toolkit toolkit = getToolkit();
        Dimension tamanoPantalla = toolkit.getScreenSize();
        f.setLocation((tamanoPantalla.width / 2) - (getWidth() / 2), (tamanoPantalla.height / 2) - (getHeight() / 2));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton button_Login;
    private javax.swing.JButton button_RegisterHere;
    private javax.swing.JButton button_RegisterHere1;
    private javax.swing.JCheckBox check_RemenberMe;
    private javax.swing.JPasswordField input_Password;
    private javax.swing.JPasswordField input_Password1;
    private javax.swing.JTextField input_User;
    private javax.swing.JTextField input_User1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel label_DontHaveAccount;
    private javax.swing.JLabel label_IconoPassword;
    private javax.swing.JLabel label_IconoSignIn;
    private javax.swing.JLabel label_IconoSignIn1;
    private javax.swing.JLabel label_IconoUser;
    private javax.swing.JLabel label_LoginImage;
    private javax.swing.JLabel label_ProyectName;
    private javax.swing.JLabel label_SignIn;
    private javax.swing.JLabel label_SignIn1;
    private javax.swing.JLabel label_ValidacionesTxt;
    private javax.swing.JLabel lblCargando;
    private javax.swing.JLabel lblCargando1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel panel_ContendorLogin;
    private javax.swing.JPanel panel_EsteticaLogin;
    private javax.swing.JPanel panel_ImageLogin;
    private javax.swing.JPanel panel_InfoLogin;
    private javax.swing.JPanel panel_Loanding;
    private javax.swing.JPanel panel_Login;
    private javax.swing.JPanel panel_Register;
    private rojerusan.componentes.RSProgressMaterial rSProgressMaterial1;
    private javax.swing.JSeparator separator_Separator1;
    // End of variables declaration//GEN-END:variables
}
