/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import findingpeople.util.CommonsFrame;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.imgcodecs.Imgcodecs; // imread, imwrite, etc
import org.opencv.videoio.VideoCapture;   // VideoCapture   

public class Recognizer extends javax.swing.JFrame {
    //Definitions

    private DaemonThread myThread = null;
    int count = 0;
    VideoCapture webSource = null;

    Mat frame = new Mat();
    MatOfByte mem = new MatOfByte();

    class DaemonThread implements Runnable {

        protected volatile boolean runnable = false;

        @Override
        public void run() {
            synchronized (this) {
                while (runnable) {
                    if (webSource.grab()) {
                        try {
                            webSource.retrieve(frame);
                            Imgcodecs.imencode(".bmp", frame, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));

                            BufferedImage buff = (BufferedImage) im;
                            Graphics g = panel_camara.getGraphics();

                            if (g.drawImage(buff, 0, 0, getWidth(), getHeight() - 150, 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                                if (runnable == false) {
                                    System.out.println("Going to wait()");
                                    this.wait();
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Error");
                        }
                    }
                }
            }
        }
    }
    /////////////////////////////////////////////////////////

    public Recognizer() {
        initComponents();
        CommonsFrame.setFrameCenter(this);
        CommonsFrame.frameAtributes(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser_TomarFoto = new javax.swing.JFileChooser();
        panel_botones = new javax.swing.JPanel();
        button_Start = new javax.swing.JButton();
        button_Pause = new javax.swing.JButton();
        button_TakeSnapchot = new javax.swing.JButton();
        button_ContinuarRegistro = new javax.swing.JButton();
        panel_camara = new javax.swing.JPanel();

        filechooser_TomarFoto.setCurrentDirectory(new java.io.File("C:\\Users\\USER\\Documents\\NetBeansProjects\\FindingPeople\\src\\findingpeople\\desaparecidos"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_botones.setBackground(new java.awt.Color(37, 47, 65));

        button_Start.setText("Iniciar");
        button_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_StartActionPerformed(evt);
            }
        });

        button_Pause.setText("Detener");
        button_Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PauseActionPerformed(evt);
            }
        });

        button_TakeSnapchot.setText("Tomar Foto");
        button_TakeSnapchot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TakeSnapchotActionPerformed(evt);
            }
        });

        button_ContinuarRegistro.setBackground(new java.awt.Color(4, 96, 194));
        button_ContinuarRegistro.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_ContinuarRegistro.setForeground(new java.awt.Color(225, 225, 225));
        button_ContinuarRegistro.setText("Continuar Registro");
        button_ContinuarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ContinuarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_botonesLayout = new javax.swing.GroupLayout(panel_botones);
        panel_botones.setLayout(panel_botonesLayout);
        panel_botonesLayout.setHorizontalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(button_Pause, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(button_TakeSnapchot, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(button_ContinuarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_botonesLayout.setVerticalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_botonesLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Pause)
                    .addComponent(button_Start)
                    .addComponent(button_TakeSnapchot)
                    .addComponent(button_ContinuarRegistro))
                .addGap(27, 27, 27))
        );

        panel_camara.setBackground(new java.awt.Color(37, 47, 65));

        javax.swing.GroupLayout panel_camaraLayout = new javax.swing.GroupLayout(panel_camara);
        panel_camara.setLayout(panel_camaraLayout);
        panel_camaraLayout.setHorizontalGroup(
            panel_camaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        panel_camaraLayout.setVerticalGroup(
            panel_camaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_camara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 369, Short.MAX_VALUE)
                .addComponent(panel_botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panel_camara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 85, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_StartActionPerformed

        webSource = new VideoCapture(0);
        myThread = new DaemonThread();
        Thread t = new Thread(myThread);
        t.setDaemon(true);
        myThread.runnable = true;
        t.start();
        button_Start.setEnabled(false);  //start button
        button_TakeSnapchot.setEnabled(true);  // stop button

    }//GEN-LAST:event_button_StartActionPerformed

    private void button_PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PauseActionPerformed

        myThread.runnable = false;
        button_Pause.setEnabled(false);
        button_Start.setEnabled(true);

        webSource.release(); //Stop Capturing	

    }//GEN-LAST:event_button_PauseActionPerformed

    private void button_TakeSnapchotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TakeSnapchotActionPerformed

        int returnVal = filechooser_TomarFoto.showSaveDialog(this);
        if (returnVal == filechooser_TomarFoto.APPROVE_OPTION) {
            File file = filechooser_TomarFoto.getSelectedFile();
            String rutaDeseada = "C:\\Users\\USER\\Documents\\NetBeansProjects\\FindingPeople\\src\\findingpeople\\desaparecidos\\";
            // Sting archivoAMostrar = filechooser_TomarFoto.getSelectedFile().getName().toString();
            Imgcodecs.imwrite(rutaDeseada + file.getName(), frame);
            rsscalelabel.RSScaleLabel.setScaleLabel(UploadPeople.label_PersonaDesaparecida, rutaDeseada + file.getName());

        } else {
            System.out.println("File access cancelled by user.");
        }

    }//GEN-LAST:event_button_TakeSnapchotActionPerformed

    private void button_ContinuarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ContinuarRegistroActionPerformed
        UploadPeople uploadPeople = new UploadPeople();
        this.hide();
        uploadPeople.show();
    }//GEN-LAST:event_button_ContinuarRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recognizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ContinuarRegistro;
    private javax.swing.JButton button_Pause;
    private javax.swing.JButton button_Start;
    private javax.swing.JButton button_TakeSnapchot;
    private javax.swing.JFileChooser filechooser_TomarFoto;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel panel_camara;
    // End of variables declaration//GEN-END:variables

}
