/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter(){
                
                @Override
                public void windowClosing(WindowEvent e){
                    int x = JOptionPane.showConfirmDialog(null, "¿Realmemte quiere salir de KeLiz System?",
                                                          "Cerrar",
                                                          JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if(x == JOptionPane.YES_OPTION){
                        e.getWindow().dispose();
                        System.out.println("Cerrar");
                    }else if(x == JOptionPane.NO_OPTION){
                        System.out.println("Seguimo'");
                    }
                }
        });
        setTitle("KeLiz System - Reportes");
        setIconImage(new ImageIcon(getClass().getResource("/findingpeople/Images/loginImage.png")).getImage());
        this.setResizable(false);
        setFrameCenter(this);
        panel_PersonasEncontradas.hide();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_FondoReportes = new javax.swing.JPanel();
        panel_Titulos = new javax.swing.JPanel();
        button_PersonasDesaparecidas = new javax.swing.JButton();
        button_PersonasEncontradas = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_PersonasDesaparecidas = new javax.swing.JPanel();
        label_PersonasDesaparecidas = new javax.swing.JLabel();
        button_MenuPrincipalEnPersonasDesaparecidas = new javax.swing.JButton();
        panel_PersonasEncontradas = new javax.swing.JPanel();
        label_PersonasEncontradas = new javax.swing.JLabel();
        button_MenuPrincipalEnPersonasEncontradas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Titulos.setBackground(new java.awt.Color(0, 0, 204));

        button_PersonasDesaparecidas.setBackground(new java.awt.Color(4, 96, 194));
        button_PersonasDesaparecidas.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        button_PersonasDesaparecidas.setForeground(new java.awt.Color(255, 255, 255));
        button_PersonasDesaparecidas.setText("Personas Desaparecidas");
        button_PersonasDesaparecidas.setBorder(null);
        button_PersonasDesaparecidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PersonasDesaparecidasActionPerformed(evt);
            }
        });

        button_PersonasEncontradas.setBackground(new java.awt.Color(0, 204, 102));
        button_PersonasEncontradas.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        button_PersonasEncontradas.setForeground(new java.awt.Color(255, 255, 255));
        button_PersonasEncontradas.setText("Personas Encontradas");
        button_PersonasEncontradas.setBorder(null);
        button_PersonasEncontradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PersonasEncontradasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TitulosLayout = new javax.swing.GroupLayout(panel_Titulos);
        panel_Titulos.setLayout(panel_TitulosLayout);
        panel_TitulosLayout.setHorizontalGroup(
            panel_TitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TitulosLayout.createSequentialGroup()
                .addComponent(button_PersonasDesaparecidas, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_PersonasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_TitulosLayout.setVerticalGroup(
            panel_TitulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_PersonasDesaparecidas, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addComponent(button_PersonasEncontradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_PersonasDesaparecidas.setBackground(new java.awt.Color(37, 47, 65));

        label_PersonasDesaparecidas.setText("Aqui van las personas Desaparecidas");

        button_MenuPrincipalEnPersonasDesaparecidas.setBackground(new java.awt.Color(4, 96, 194));
        button_MenuPrincipalEnPersonasDesaparecidas.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_MenuPrincipalEnPersonasDesaparecidas.setForeground(new java.awt.Color(225, 225, 225));
        button_MenuPrincipalEnPersonasDesaparecidas.setText("Menu Principal");
        button_MenuPrincipalEnPersonasDesaparecidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MenuPrincipalEnPersonasDesaparecidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_PersonasDesaparecidasLayout = new javax.swing.GroupLayout(panel_PersonasDesaparecidas);
        panel_PersonasDesaparecidas.setLayout(panel_PersonasDesaparecidasLayout);
        panel_PersonasDesaparecidasLayout.setHorizontalGroup(
            panel_PersonasDesaparecidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PersonasDesaparecidasLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(panel_PersonasDesaparecidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PersonasDesaparecidasLayout.createSequentialGroup()
                        .addComponent(button_MenuPrincipalEnPersonasDesaparecidas)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PersonasDesaparecidasLayout.createSequentialGroup()
                        .addComponent(label_PersonasDesaparecidas, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))))
        );
        panel_PersonasDesaparecidasLayout.setVerticalGroup(
            panel_PersonasDesaparecidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PersonasDesaparecidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MenuPrincipalEnPersonasDesaparecidas)
                .addGap(73, 73, 73)
                .addComponent(label_PersonasDesaparecidas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_PersonasDesaparecidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 809, -1));

        panel_PersonasEncontradas.setBackground(new java.awt.Color(37, 47, 65));

        label_PersonasEncontradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_PersonasEncontradas.setText("Aqui van las personas Encontradas");

        button_MenuPrincipalEnPersonasEncontradas.setBackground(new java.awt.Color(4, 96, 194));
        button_MenuPrincipalEnPersonasEncontradas.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_MenuPrincipalEnPersonasEncontradas.setForeground(new java.awt.Color(225, 225, 225));
        button_MenuPrincipalEnPersonasEncontradas.setText("Menu Principal");
        button_MenuPrincipalEnPersonasEncontradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MenuPrincipalEnPersonasEncontradasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_PersonasEncontradasLayout = new javax.swing.GroupLayout(panel_PersonasEncontradas);
        panel_PersonasEncontradas.setLayout(panel_PersonasEncontradasLayout);
        panel_PersonasEncontradasLayout.setHorizontalGroup(
            panel_PersonasEncontradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PersonasEncontradasLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(label_PersonasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PersonasEncontradasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_MenuPrincipalEnPersonasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_PersonasEncontradasLayout.setVerticalGroup(
            panel_PersonasEncontradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PersonasEncontradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_MenuPrincipalEnPersonasEncontradas)
                .addGap(92, 92, 92)
                .addComponent(label_PersonasEncontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_PersonasEncontradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout panel_FondoReportesLayout = new javax.swing.GroupLayout(panel_FondoReportes);
        panel_FondoReportes.setLayout(panel_FondoReportesLayout);
        panel_FondoReportesLayout.setHorizontalGroup(
            panel_FondoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Titulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        panel_FondoReportesLayout.setVerticalGroup(
            panel_FondoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FondoReportesLayout.createSequentialGroup()
                .addComponent(panel_Titulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_FondoReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_FondoReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_PersonasDesaparecidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PersonasDesaparecidasActionPerformed
        button_PersonasDesaparecidas.setFont(new Font("Tahoma", 1, 22));
        button_PersonasEncontradas.setFont(new Font("Tahoma", 1, 20));
        panel_PersonasDesaparecidas.show();
        panel_PersonasEncontradas.hide();
    }//GEN-LAST:event_button_PersonasDesaparecidasActionPerformed

    private void button_PersonasEncontradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PersonasEncontradasActionPerformed

        button_PersonasDesaparecidas.setFont(new Font("Tahoma", 1, 20));
        button_PersonasEncontradas.setFont(new Font("Tahoma", 1, 22));
        panel_PersonasDesaparecidas.hide();
        panel_PersonasEncontradas.show();

    }//GEN-LAST:event_button_PersonasEncontradasActionPerformed

    private void button_MenuPrincipalEnPersonasDesaparecidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MenuPrincipalEnPersonasDesaparecidasActionPerformed
        Container container = new Container();
        this.hide();
        container.show();
    }//GEN-LAST:event_button_MenuPrincipalEnPersonasDesaparecidasActionPerformed

    private void button_MenuPrincipalEnPersonasEncontradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MenuPrincipalEnPersonasEncontradasActionPerformed
        Container container = new Container();
        this.hide();
        container.show();
    }//GEN-LAST:event_button_MenuPrincipalEnPersonasEncontradasActionPerformed

    private void setFrameCenter(JFrame f) {

        Toolkit toolkit = getToolkit();
        Dimension tamanoPantalla = toolkit.getScreenSize();
        f.setLocation((tamanoPantalla.width / 2) - (getWidth() / 2), (tamanoPantalla.height / 2) - (getHeight() / 2));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_MenuPrincipalEnPersonasDesaparecidas;
    private javax.swing.JButton button_MenuPrincipalEnPersonasEncontradas;
    private javax.swing.JButton button_PersonasDesaparecidas;
    private javax.swing.JButton button_PersonasEncontradas;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel label_PersonasDesaparecidas;
    private javax.swing.JLabel label_PersonasEncontradas;
    private javax.swing.JPanel panel_FondoReportes;
    private javax.swing.JPanel panel_PersonasDesaparecidas;
    private javax.swing.JPanel panel_PersonasEncontradas;
    private javax.swing.JPanel panel_Titulos;
    // End of variables declaration//GEN-END:variables
}
