/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findingpeople;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class UploadPeople extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public UploadPeople() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter(){
                
                @Override
                public void windowClosing(WindowEvent e){
                    int x = JOptionPane.showConfirmDialog(null, "¿¿Realmemte quiere salir de ReLiz System?",
                                                          "Cerrar",
                                                          JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if(x == JOptionPane.YES_OPTION){
                        e.getWindow().dispose();
                        System.out.println("Cerrar");
                    }else{
                        System.out.println("Seguimo'");
                    }
                }
        });
        setFrameCenter(this);
        setTitle("KeLiz System - Registro de Desaparecidos");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Sexo = new javax.swing.ButtonGroup();
        panel_FondoUploadPeople = new javax.swing.JPanel();
        label_RegistroDesaparecidos = new javax.swing.JLabel();
        button_MenuPrincipal = new javax.swing.JButton();
        input_Nombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        label_Correo = new javax.swing.JLabel();
        label_Celular = new javax.swing.JLabel();
        label_Sexo = new javax.swing.JLabel();
        radiobutton_Hombre = new javax.swing.JRadioButton();
        radiobutton_Mujer = new javax.swing.JRadioButton();
        button_SubirFoto = new javax.swing.JButton();
        label_Foto = new javax.swing.JLabel();
        input_Correo = new javax.swing.JTextField();
        input_Celular = new javax.swing.JTextField();
        button_Registro = new javax.swing.JButton();
        button_TomarFoto = new javax.swing.JButton();
        label_PersonaDesaparecida = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_FondoUploadPeople.setBackground(new java.awt.Color(37, 47, 65));

        label_RegistroDesaparecidos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        label_RegistroDesaparecidos.setForeground(new java.awt.Color(255, 255, 255));
        label_RegistroDesaparecidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_RegistroDesaparecidos.setText("Registro de Persona Desaparecida");

        button_MenuPrincipal.setBackground(new java.awt.Color(4, 96, 194));
        button_MenuPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_MenuPrincipal.setForeground(new java.awt.Color(225, 225, 225));
        button_MenuPrincipal.setText("Menu Principal");
        button_MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MenuPrincipalActionPerformed(evt);
            }
        });

        input_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_NombreActionPerformed(evt);
            }
        });
        input_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_NombreKeyReleased(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        label_Correo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_Correo.setForeground(new java.awt.Color(255, 255, 255));
        label_Correo.setText("Correo a contactar");

        label_Celular.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_Celular.setForeground(new java.awt.Color(255, 255, 255));
        label_Celular.setText("Celular a contactar");

        label_Sexo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_Sexo.setForeground(new java.awt.Color(255, 255, 255));
        label_Sexo.setText("Sexo");

        radiobutton_Hombre.setBackground(new java.awt.Color(37, 47, 65));
        buttonGroup_Sexo.add(radiobutton_Hombre);
        radiobutton_Hombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radiobutton_Hombre.setForeground(new java.awt.Color(255, 255, 255));
        radiobutton_Hombre.setText("Hombre");

        radiobutton_Mujer.setBackground(new java.awt.Color(37, 47, 65));
        buttonGroup_Sexo.add(radiobutton_Mujer);
        radiobutton_Mujer.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radiobutton_Mujer.setForeground(new java.awt.Color(255, 255, 255));
        radiobutton_Mujer.setText("Mujer");

        button_SubirFoto.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_SubirFoto.setText("Subir Foto");
        button_SubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SubirFotoActionPerformed(evt);
            }
        });

        label_Foto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_Foto.setForeground(new java.awt.Color(255, 255, 255));
        label_Foto.setText("Foto");

        input_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_CorreoActionPerformed(evt);
            }
        });
        input_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_CorreoKeyReleased(evt);
            }
        });

        input_Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_CelularActionPerformed(evt);
            }
        });
        input_Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_CelularKeyReleased(evt);
            }
        });

        button_Registro.setBackground(new java.awt.Color(4, 96, 194));
        button_Registro.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_Registro.setForeground(new java.awt.Color(225, 225, 225));
        button_Registro.setText("Registrar");
        button_Registro.setEnabled(false);
        button_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RegistroActionPerformed(evt);
            }
        });

        button_TomarFoto.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_TomarFoto.setText("Tomar Foto");
        button_TomarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TomarFotoActionPerformed(evt);
            }
        });

        label_PersonaDesaparecida.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_PersonaDesaparecida.setForeground(new java.awt.Color(255, 255, 255));
        label_PersonaDesaparecida.setText("Persona Desapa");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 204));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 204));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 204));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panel_FondoUploadPeopleLayout = new javax.swing.GroupLayout(panel_FondoUploadPeople);
        panel_FondoUploadPeople.setLayout(panel_FondoUploadPeopleLayout);
        panel_FondoUploadPeopleLayout.setHorizontalGroup(
            panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_Celular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(label_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                        .addComponent(button_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(button_MenuPrincipal)
                        .addGap(22, 22, 22))
                    .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                        .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                                    .addComponent(radiobutton_Hombre)
                                    .addGap(11, 11, 11)
                                    .addComponent(radiobutton_Mujer))
                                .addComponent(input_Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                .addComponent(input_Celular)
                                .addComponent(input_Nombre))
                            .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_TomarFoto)
                                    .addComponent(button_SubirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(label_PersonaDesaparecida, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(label_RegistroDesaparecidos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_FondoUploadPeopleLayout.setVerticalGroup(
            panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_RegistroDesaparecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiobutton_Hombre)
                            .addComponent(radiobutton_Mujer)
                            .addComponent(jLabel11)))
                    .addComponent(label_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_FondoUploadPeopleLayout.createSequentialGroup()
                        .addComponent(button_TomarFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_SubirFoto))
                    .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_PersonaDesaparecida, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panel_FondoUploadPeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        input_Nombre.getAccessibleContext().setAccessibleName("txtNombre");
        input_Correo.getAccessibleContext().setAccessibleName("txtCorreo");
        input_Celular.getAccessibleContext().setAccessibleName("txtelefono");
        jLabel8.getAccessibleContext().setAccessibleName("rqrd_Nombre");
        jLabel9.getAccessibleContext().setAccessibleName("rqrd_email");
        jLabel10.getAccessibleContext().setAccessibleName("rqrd_tel");
        jLabel11.getAccessibleContext().setAccessibleName("rqrd_sexo");
        jLabel12.getAccessibleContext().setAccessibleName("rqrd_foto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_FondoUploadPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_FondoUploadPeople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MenuPrincipalActionPerformed
       Container container = new Container();
       this.hide();
       container.show();
    }//GEN-LAST:event_button_MenuPrincipalActionPerformed

    private void button_SubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SubirFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_SubirFotoActionPerformed

    private void button_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_RegistroActionPerformed

    private void button_TomarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TomarFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_TomarFotoActionPerformed

    private void input_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_CorreoActionPerformed

    private void input_CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_CelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_CelularActionPerformed

    private void input_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_NombreActionPerformed

    private void input_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_NombreKeyReleased
        validar();
    }//GEN-LAST:event_input_NombreKeyReleased

    private void input_CorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_CorreoKeyReleased
        validar();
    }//GEN-LAST:event_input_CorreoKeyReleased

    private void input_CelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_CelularKeyReleased
        validar();
    }//GEN-LAST:event_input_CelularKeyReleased

        private void setFrameCenter(JFrame f) {

        Toolkit toolkit = getToolkit();
        Dimension tamanoPantalla = toolkit.getScreenSize();
        f.setLocation((tamanoPantalla.width / 2) - (getWidth() / 2), (tamanoPantalla.height / 2) - (getHeight() / 2));

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadPeople().setVisible(true);
            }
        });
    };
    
    public void validar(){
    if(input_Nombre.getText().isEmpty()){
       jLabel8.setText("Required Field");
    }else{
        jLabel8.setText("");
    }
    if(input_Correo.getText().isEmpty()){
       jLabel9.setText("Required Field");
    }else if(!input_Correo.getText().contains("@") || !input_Correo.getText().contains(".")){
        jLabel9.setText("Invalid Email");
    }else{
        jLabel9.setText("");
    }
    if(input_Celular.getText().isEmpty()){
       jLabel10.setText("Required Field");
    }else{
        jLabel10.setText("");
    }
    if(input_Celular.getText().isEmpty() || input_Correo.getText().isEmpty() || 
            input_Nombre.getText().isEmpty() || jLabel9.getText().equals("Invalid Email")){
        button_Registro.setEnabled(false);
    }else{
         button_Registro.setEnabled(true);
    }
   
    };
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Sexo;
    private javax.swing.JButton button_MenuPrincipal;
    private javax.swing.JButton button_Registro;
    private javax.swing.JButton button_SubirFoto;
    private javax.swing.JButton button_TomarFoto;
    private javax.swing.JTextField input_Celular;
    private javax.swing.JTextField input_Correo;
    private javax.swing.JTextField input_Nombre;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_Celular;
    private javax.swing.JLabel label_Correo;
    private javax.swing.JLabel label_Foto;
    private javax.swing.JLabel label_PersonaDesaparecida;
    private javax.swing.JLabel label_RegistroDesaparecidos;
    private javax.swing.JLabel label_Sexo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panel_FondoUploadPeople;
    private javax.swing.JRadioButton radiobutton_Hombre;
    private javax.swing.JRadioButton radiobutton_Mujer;
    // End of variables declaration//GEN-END:variables
}
